name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Specify the version of Node.js you need

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      - name: Deploy files via SCP
        run: |
          rsync -avz --delete-after ./build/ user@your-server-ip:/home/master/applications/ajxhjxagtg/public_html
        env:
          SSH_KNOWN_HOSTS: your-server-ip